SELECT e.FIRST_NAME,e.LAST_NAME,D.DEPARTMENT_ID,D.DEPARTMENT_NAME
FROM EMPLOYEES e
         INNER JOIN DEPARTMENTS D on e.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT  f.First_name,f.Last_name, d.Department_name,l.STATE_PROVINCE,l.City
From EMPLOYEES f
join DEPARTMENTS d on f.DEPARTMENT_ID = d.DEPARTMENT_ID
join LOCATIONS l on d.LOCATION_ID = l.LOCATION_ID;

SELECT EMPLOYEES.First_name,EMPLOYEES.Last_name,EMPLOYEES.Salary,JOB_GRADES.GRADE
FROM EMPLOYEES
INNER JOIN JOB_GRADES
on EMPLOYEES.Salary BETWEEN JOB_GRADES.LOWEST_SAL AND JOB_GRADES.HIGHEST_SAL;

SELECT E.First_Name,E.Last_name,d.Department_id,d.Department_name
FROM EMPLOYEES E
JOIN DEPARTMENTS d  On e.DEPARTMENT_ID=d.DEPARTMENT_ID
Where d.DEPARTMENT_ID IN(80,40);

SELECT FIRST_NAME,LAST_NAME,d.DEPARTMENT_ID,l.City,l.State_province
From EMPLOYEES e
JOIN DEPARTMENTS d on e.DEPARTMENT_ID = d.DEPARTMENT_ID
JOIN LOCATIONS l on d.LOCATION_ID = l.LOCATION_ID
Where e.FIRST_NAME LIKE '%z%';


SELECT E.FIRST_NAME,E.LAST_NAME,D.DEPARTMENT_ID,D.DEPARTMENT_NAME
FROM EMPLOYEES E
RIGHT OUTER JOIN DEPARTMENTS D on E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT E.FIRST_NAME,E.LAST_NAME,D.DEPARTMENT_ID,D.DEPARTMENT_NAME
From DEPARTMENTS D
LEFT OUTER JOIN EMPLOYEES E on D.DEPARTMENT_ID=E.DEPARTMENT_ID;

SELECT E.FIRST_NAME AS EMPLOYEE,M.FIRST_NAME AS MANAGER
FROM EMPLOYEES E
join EMPLOYEES M on E.MANAGER_ID = M.EMPLOYEE_ID
ORDER BY MANAGER;

SELECT FIRST_NAME,LAST_NAME,SALARY
FROM EMPLOYEES
WHERE SALARY>(Select SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID=163);