Select Hire_date,extract(Month from HIRE_DATE) from EMPLOYEES;

SELECT  FIRST_NAME, HIRE_DATE, EXTRACT(year from HIRE_DATE)from EMPLOYEES
where EXTRACT(year from HIRE_DATE) =2008;

SELECT  FIRST_NAME, HIRE_DATE, EXTRACT(year from HIRE_DATE)from EMPLOYEES
where EXTRACT(year from HIRE_DATE) between 2001 and 2003;

SELECT EXTRACT(year from HIRE_DATE) AS HIRED_YEAR,
       COUNT(*)AS EMPLOYEE_COUNT
FROM EMPLOYEES
GROUP BY EXTRACT(year from HIRE_DATE)HAVING COUNT(*)>15
ORDER BY 1;
--ORDER BY FIRST COMUMN IN SELECT STATEMENT